#!/usr/local/python

"""
Project Euler Problem 2
Even Fibonacci numbers
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
"""
import sys


def main(num):
    total = 0
    i = 1
    nextI = 1
    while i <= num:
        prevI = i
        i = nextI
        nextI += prevI
        if 0 == i % 2:
            total += i
    print "The sum of the even numbers of Fibonacci series where the highest number is " + str(num) + ": " + str(total)


if __name__ == "__main__":
    main(int(sys.argv[1]))
